version: '2'
services:
    jekyll:
          image: grahamc/jekyll
          volumes:
              - ./:/src
          command: [build,--watch]
    nginx:
          image: nginx
          ports:
            - "8080:80"
          volumes:
              - ./_site:/usr/share/nginx/html
